import { BookOpen, PlaySquare } from "lucide-react";
import { Link } from "react-router-dom";
import type { FAQItem, LearningResource, VideoContent } from "@/content/site";
import { Button } from "@/components/ui/button";

export function VideoIntro({ video }: { video: VideoContent }) {
  if (video.videoUrl) return <figure className="overflow-hidden border border-border bg-card"><div className="aspect-video bg-muted"><video className="h-full w-full object-cover" controls poster={video.poster}><source src={video.videoUrl} />Your browser does not support embedded video.</video></div><figcaption className="border-t border-border px-4 py-3"><p className="font-semibold">{video.title}</p>{video.description && <p className="mt-1 text-sm text-muted-foreground">{video.description}</p>}</figcaption></figure>;
  return <section className="flex aspect-video flex-col justify-between border border-dashed border-border bg-muted/40 p-5 sm:p-6" aria-label={`${video.title}: video coming soon`}><div><PlaySquare className="h-7 w-7 text-primary" aria-hidden="true" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-primary">Video coming soon</p><h2 className="mt-2 text-xl font-semibold">{video.title}</h2></div>{video.description && <p className="max-w-md text-sm leading-relaxed text-muted-foreground">{video.description}</p>}</section>;
}

export function SubjectExperience({ items }: { items: Array<{ title: string; detail?: string }> }) { return <div className="grid divide-y divide-border border-y border-border sm:grid-cols-2 sm:divide-x sm:divide-y-0">{items.map(item => <div className="px-4 py-4" key={item.title}><h3 className="font-semibold">{item.title}</h3>{item.detail && <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{item.detail}</p>}</div>)}</div>; }
export function TeachingApproach({ items }: { items: Array<{ title: string; detail: string }> }) { return <div className="grid gap-x-8 gap-y-5 border-y border-border py-5 sm:grid-cols-2">{items.map((item, index) => <article key={item.title}><p className="text-xs font-bold text-primary">0{index + 1}</p><h3 className="mt-2 font-semibold">{item.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{item.detail}</p></article>)}</div>; }
export function EngagementProcess({ items }: { items: Array<{ title: string; detail: string }> }) { return <ol className="grid divide-y divide-border border-y border-border md:grid-cols-3 md:divide-x md:divide-y-0">{items.map((item, index) => <li className="px-4 py-4" key={item.title}><p className="text-xs font-bold text-primary">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-2 font-semibold">{item.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{item.detail}</p></li>)}</ol>; }

export function LearningResourceCard({ resource }: { resource: LearningResource }) { return <article className="border-t border-border pt-4"><div className="flex items-center justify-between gap-3 text-xs font-semibold uppercase tracking-wide text-primary"><span>{resource.subject} · {resource.topic}</span><span>{resource.resourceType}</span></div><h3 className="mt-3 text-lg font-semibold">{resource.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{resource.description}</p><p className="mt-3 text-xs text-muted-foreground">{resource.level}{resource.publishedAt ? ` · ${resource.publishedAt}` : ""}</p>{resource.embedUrl && <a href={resource.embedUrl} className="mt-4 inline-block text-sm font-semibold text-primary">Open resource</a>}</article>; }
export function LearningLibraryGrid({ resources, subject }: { resources: LearningResource[]; subject?: "Math" | "Physics" }) { const items = subject ? resources.filter(resource => resource.subject === subject) : resources; if (items.length === 0) return <div className="border-y border-border bg-muted/40 px-6 py-9 text-center"><BookOpen className="mx-auto h-7 w-7 text-primary" /><h3 className="mt-3 font-semibold">The learning library is being prepared.</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Lessons and worked examples will appear here as they are ready. The collection is intentionally empty for now.</p></div>; return <div className="grid gap-x-7 gap-y-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(resource => <LearningResourceCard key={resource.id} resource={resource} />)}</div>; }
export function CallToAction({ title, description, action = "Start a Conversation" }: { title: string; description: string; action?: string }) { return <section className="border-y border-border bg-soft-gradient py-9"><div className="section-container flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold tracking-tight">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{description}</p></div><Button asChild><Link to="/contact">{action}</Link></Button></div></section>; }
export function CompactFaq({ items }: { items: FAQItem[] }) { return <div className="border-y border-border">{items.map(item => <details className="group border-b border-border last:border-b-0" key={item.question}><summary className="cursor-pointer py-4 text-sm font-semibold">{item.question}</summary><p className="pb-4 text-sm leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div>; }
