import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/site/SiteLayout";
import { ConversationButton, PrincipleCard, SectionHeading, SubjectCard } from "@/components/site/ContentBlocks";
import { FAQ, Testimonials } from "@/components/site/TrustContent";
import { faqs, site, subjects, teachingPrinciples, testimonials } from "@/content/site";
import soumyaPhoto from "@/assets/SoumyaSpeaking.jpeg";

export default function Home() {
  return <PageShell>
    <section className="overflow-hidden bg-soft-gradient py-12 sm:py-16"><div className="section-container grid items-center gap-8 lg:grid-cols-[1.15fr_.85fr]">
      <div><p className="mb-4 text-sm font-semibold uppercase tracking-[0.16em] text-primary">Independent Math & Physics teaching</p><h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">{site.positioning}</h1>
        <p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Experienced, patient teaching for middle- and high-school students—focused on concept clarity, confidence, and independent problem solving.</p>
        <p className="mt-5 text-sm font-semibold leading-relaxed text-foreground">Grades VIII–X <span aria-hidden="true">·</span> One-to-one & small groups <span aria-hidden="true">·</span> US & International curricula</p>
        <div className="mt-6 flex flex-wrap gap-3"><ConversationButton /><Button size="lg" variant="outline" asChild><Link to="/learn">Explore Learning</Link></Button></div>
      </div><div className="mx-auto max-w-[17rem] sm:max-w-sm"><img src={soumyaPhoto} alt="Soumya teaching" className="aspect-square w-full rounded-3xl object-cover shadow-elegant" /></div>
    </div></section>
    <section className="py-12 sm:py-16"><div className="section-container"><SectionHeading eyebrow="Subjects" title="Two clear pathways" description="Focused teaching in the subjects where understanding makes the biggest difference." /><div className="grid gap-5 md:grid-cols-2"><SubjectCard title="Math" description={subjects.math.summary} href="/math" /><SubjectCard title="Physics" description={subjects.physics.summary} href="/physics" /></div></div></section>
    <section className="bg-muted/50 py-12 sm:py-16"><div className="section-container"><SectionHeading eyebrow="Why Soumya" title="Experience that stays focused on the student" /><div className="grid border-y border-border py-5 text-center sm:grid-cols-2 lg:grid-cols-4">{["20+ years teaching", "Math & Physics", "IB, IGCSE & US curricula", "India, Singapore & USA"].map(item => <div key={item} className="px-3 py-2 text-sm font-semibold">{item}</div>)}</div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{teachingPrinciples.map(principle => <PrincipleCard key={principle.title} {...principle} />)}</div><p className="mx-auto mt-6 max-w-2xl text-center text-sm leading-relaxed text-muted-foreground">Progress is encouraged through positive reinforcement and clear guidance about what additional effort can help a student achieve.</p></div></section>
    <section className="py-12 sm:py-16"><div className="section-container grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Curriculum experience</p><h2 className="mt-2 text-2xl font-bold">Real experience across the curricula students bring to class.</h2><p className="mt-3 leading-relaxed text-muted-foreground">{site.experience} across Math and Physics, through one-to-one and small-group teaching.</p></div><div className="grid gap-5 sm:grid-cols-2"><div><p className="font-semibold text-primary">Math</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Algebra 2, Geometry B, IB SL Math, IGCSE, and A Levels</p></div><div><p className="font-semibold text-primary">Physics</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">IB SL Physics, Grades IX–X and XI–XII, plus JEE-oriented preparation</p></div></div></div></section>
    <section className="bg-soft-gradient py-12 sm:py-16"><div className="section-container flex flex-col items-center justify-between gap-5 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Learn with Soumya</p><h2 className="mt-2 text-2xl font-bold">A learning library, built with care.</h2><p className="mt-2 max-w-xl leading-relaxed text-muted-foreground">Selected Math and Physics lessons will gradually be available for students who want to learn at their own pace.</p></div><Button variant="outline" asChild><Link to="/learn">Explore Learning</Link></Button></div></section>
    <section className="py-10 sm:py-12"><div className="section-container"><div className="flex flex-col justify-between gap-5 border-y border-border py-6 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Getting started</p><h2 className="mt-2 text-2xl font-bold">Tell Soumya about the student.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Share the grade, subject, curriculum, and where help is needed. The first conversation helps identify the right approach.</p></div><ConversationButton /></div></div></section>
    <Testimonials items={testimonials} />
    <FAQ items={faqs} />
    <section className="bg-foreground py-12 text-background"><div className="section-container flex flex-col items-center justify-between gap-5 sm:flex-row"><div><h2 className="text-2xl font-bold">Ready to get started?</h2><p className="mt-2 text-background/75">Start a conversation about your child’s learning needs.</p></div><Button size="lg" variant="secondary" asChild><Link to="/contact">Start a Conversation</Link></Button></div></section>
  </PageShell>;
}
